modLoader="javafml"
loaderVersion="[1,)"
license="mit"

[[mods]]
modId="pastelstorage"
version="${version}"
displayName="Pastel Storage"
logoFile="assets/pastelstorage/icon.png"
authors="BulbyVR"
description='''Storage addons for Pastel'''

[[dependencies.pastelstorage]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.pastelstorage]]
modId="pastel"
type="required"
versionRange="${pastel_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.pastelstorage]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"